#!/bin/bash

# Run this script in the root dir of the repo within the container launched by `./run`.


set -e
thisdir="$(pwd)"

if [ -z "${PKG}" ]; then
    # Infer the package name.
    # This is the name of the package code directory under `src/`, also the "import" name.
    # This does not need to be the "project" name defined in `pyproject.toml`, which is for `pypi` and `pip`,
    # related to install/uninstall.
    rm -rf "${thisdir}/src"/*egg-info  # these could have been created during package build
    pkg="$(ls "${thisdir}"/src/)"
    if [[ "${pkg}" == '' || $pkg = *' '* ]]; then  # zero or multiple subdirectories
        >&2 echo "unable to infer package name"
        exit 1
    fi
    PKG=${pkg%/}  # remove '/' at the end
fi

SRC="${thisdir}"/src/${PKG}
TESTS="${thisdir}"/tests


echo
echo --- running bandit ---
echo
bandit -r -lll ${SRC}
bandit -r -lll ${TESTS}


echo
echo --- running ruff ---
echo
ruff ${SRC}


echo
echo --- running mypy ---
echo
# python -m mypy --show-error-codes --disable-error-code import ${SRC} || true
python -m mypy ${SRC} || true  # MyPy errors do not halt this script


# echo
# echo --- running pylint ---
# echo
# # python -m pylint --disable=C0103,C0114,C0115,C0116,C0301,C0302,C0303,C0305,R0902,R0903,R1705,W0201,W0223 "${SRC}" || pylint-exit $?
# python -m pylint ${SRC} || pylint-exit $?


echo
echo --- running tests ---
echo
py.test --cov=${SRC} ${TESTS}
# coverage run --source="${thisdir}/src" -m pytest -n auto ${TESTS}
# coverage report -m
# Test coverage target is specified in `pyproject.toml`.
