#!/bin/bash

# Run this script in the root dir of the repo within the container launched by `./run`.


set -e


SRC=$(pwd)/src/${PROJ//-/_}
TESTS=$(pwd)/tests


echo
echo --- running bandit ---
echo
bandit -r -lll ${SRC}
bandit -r -lll ${TESTS}

echo
echo --- running flake8 ---
echo
python -m flake8 --extend-ignore E203,E231,E501 "${SRC}"

echo
echo --- running mypy ---
echo
python -m mypy --show-error-codes --disable-error-code import ${SRC} || true

echo
echo --- running pylint ---
echo
python -m pylint --disable=C0103,C0114,C0115,C0116,C0301,C0302,C0303,C0305,R0902,R0903,R1705,W0201,W0223 "${SRC}" || pylint-exit $?
# python -m pylint --errors-only ${SRC} || pylint-exit $?


echo
echo --- running tests ---
echo
py.test --cov=${PROJ//-/_} --cov-report term-missing ${TESTS}
# Test coverage target is specified in `pyproject.toml`.

# coverage run --data-file=/tmp/.coverage --source=${SRC} -m pytest ${TESTS} -n auto
# coverage report --data-file=/tmp/.coverage
