#!/bin/bash


set -e
remote="$1"
url="$2"

thisfile="${BASH_SOURCE[0]}"
thisdir="$(cd "$(dirname "${thisfile}")"; pwd)"
if [[ "$(basename "${thisdir}")" != .githooks ]]; then
    # In this case, this script is not being executed directly;
    # rather, it is being "sourced" from another repo. The sourcing
    # script should have ensured that `pwd` is the repo's root directory.
    rootdir="$(pwd)"
else
    rootdir="$(dirname "${thisdir}")"
fi


# Infer package name, assuming a single directory exists under `src/`.
rm -rf "${rootdir}/src/*egg-info"
pkg="$(ls "${rootdir}/src/")"
if [[ "${pkg}" == *' '* ]]; then
    >&2 echo "unable to infer package name"
    exit 1
fi
pkg="${pkg%/}"


SRC="${rootdir}/src/${pkg}"
status=0

changed=$(python3 -m black --check -q "${SRC}"; echo $?)
if [[ "${changed}" != 0 ]]; then
    echo ==\> -\> -\> Formatting code by \`black\` ...
    python3 -m black "${SRC}"
    echo
    echo Please add the reformatted files in a new commit and push again.
    echo
    status=1
fi


changed=0
ruff "${SRC}" || changed=1
if [[ "${changed}" == 1 ]]; then
    echo ==\> -\> -\> Fixing some issues by \`ruff --fix\` ...
    ruff --fix "${SRC}"
    echo
    echo Please examine the issues reported/fixed by \`ruff\` and commit/push again.
    echo
    status=1
fi


# Running bandit for security issues
python3 -m bandit -r -q -lll "${rootdir}"


exit "${status}"


