#!/bin/bash

set -e

# Although we check `--local` anywhere in the command,
# it's recommended to specify it before image name.
use_local=no
for arg in "$@"; do
    if [[ "${arg}" == --local ]]; then
        use_local=yes
        break
    fi
done

TINY=zppz/tiny:21.01.02
if [[ "${use_local}" == yes ]]; then
    MINI=$(bash -c "$(docker run --rm ${TINY} cat /usr/tools/find-local-image)" -- zppz/mini)
else
    MINI=$(bash -c "$(docker run --rm ${TINY} cat /usr/tools/find-image)" -- zppz/mini)
fi

cmd="$(docker run --rm ${MINI} cat /usr/tools/run-docker)"
bash -c "${cmd}" -- $@
