#!/bin/bash

set -e

TINY=zppz/tiny:21.01.02
NAMESPACE=zppz

THISDIR="$( pwd )"
REPO=$(basename "${THISDIR}")
NAME=${REPO}

MINI=$(bash -c "$(docker run --rm ${TINY} cat /usr/tools/find-image)" -- zppz/mini)
TAG=$(docker run --rm ${TINY} make-datetime-version)

if [ -d "${THISDIR}/.git" ]; then
    BRANCH=$(cat "${THISDIR}/.git/HEAD")
    BRANCH="${BRANCH##*/}"
else
    BRANCH=branch
fi

PY_PKG_NAME=$(grep '^name\s*=\s*[a-zA-Z][a-zA-Z0-9_-]*$' "${THISDIR}/setup.cfg")
PY_PKG_NAME=$(echo "${PY_PKG_NAME#*=}" | xargs | tr '-' '_')
# `xargs` removes leading and trailing spaces.

COV_FAIL_UNDER=50  # use 0 to turn off tests
DEV_OPTS=

while [[ $# > 0 ]]; do
    if [[ "$1" == --cov-fail-under=* ]]; then
        COV_FAIL_UNDER="$1"
        COV_FAIL_UNDER="${COV_FAIL_UNDER#--cov-fail-under=}"
        shift
    elif [[ "$1" == --cov-fail-under ]]; then
        shift
        if [[ $# == 0 ]]; then
            >&2 echo "missing covarage requirement after --cov-fail-under"
            exit 1
        fi
        COV_FAIL_UNDER="$1"
        shift
    else
        DEV_OPTS="${DEV_OPTS} $1"
        # All unrecognized options are passed on to
        # the `docker build` command for the dev image.
        # These may contain, e.g. `--build-arg ...`.
        shift
    fi
done



function build-branch {
    # A project image's branched version is built on top of its
    # 'dev' version. The only addition to the parent image is to
    # install the repo's code (typically a Python package) in
    # the image.
    local parent="$1"
    local name="$2"

    local build_dir="/tmp/${REPO}"
    rm -rf ${build_dir}
    mkdir -p ${build_dir}/src
    cp -R ${THISDIR}/src ${build_dir}/src/src
    cp -R ${THISDIR}/tests ${build_dir}/src/tests
    cp ${THISDIR}/setup.cfg ${build_dir}/src/
    cp ${THISDIR}/README.md ${build_dir}/src/
    [ -d ${THISDIR}/bin ] && cp -R ${THISDIR}/bin ${build_dir}/src/bin
    [ -d ${THISDIR}/sysbin ] && cp -R ${THISDIR}/sysbin ${build_dir}/src/sysbin
    [ -f ${THISDIR}/setup.py ] && cp ${THISDIR}/setup.py ${build_dir}/src/
    [ -f ${THISDIR}/pyproject.toml ] && cp ${THISDIR}/pyproject.toml ${build_dir}/src/
    [ -f ${THISDIR}/MANIFEST.in ] && cp ${THISDIR}/MANIFEST.in ${build_dir}/src/

    cat > "${build_dir}/Dockerfile" << EOF
FROM ${parent}
USER root

ENV IMAGE_PARENT ${parent}

RUN mkdir -p /tmp/build
COPY src/ /tmp/build
RUN cd /tmp/build \\
    && python -m pip install --no-cache-dir . \\
    && mkdir -p /opt/${REPO} \\
    && mv -f tests "/opt/${REPO}/" \\
    && ( if [ -d bin ]; then mv -f bin "/opt/${REPO}/"; fi ) \\
    && ( if [ -d sysbin ]; then mkdir -p /usr/local/bin && mv sysbin/* /usr/local/bin/; fi ) \\
    && cd / \\
    && rm -rf /tmp/build
EOF

    docker build -t ${name} "${build_dir}" || return 1
    rm -rf "${build_dir}"
}


function build-test {
    local parent="$1"  # this is the branch image
    local name="$2"

    local build_dir=/tmp/src
    rm -rf ${build_dir}
    mkdir -p ${build_dir}/src
    cp -R ${THISDIR}/{src,tests} ${build_dir}/src || return 1
    [ -d ${THISDIR}/bin ] && cp -R ${THISDIR}/bin ${build_dir}/src

    cat > "${build_dir}/Dockerfile" <<EOF
FROM ${parent}
USER root
RUN python -m pip install --no-cache-dir bandit mypy pyflakes pylint radon pytest-cov pytest-sugar
COPY src /tmp/src
COPY --from=${MINI} /usr/tools/check-n-test /usr/local/bin
EOF
    docker build -t ${name} ${build_dir} || return 1
    rm -rf ${build_dir}
}



start_time=$(date)

echo
echo building for dev image
echo
echo
echo '############################'
echo "start building dev image"
echo '----------------------------'
echo
dev_img_name="${NAMESPACE}/${NAME}:${TAG}"
docker build -t ${dev_img_name} ${DEV_OPTS} ${THISDIR}/docker
echo


echo
echo '############################'
echo "start building branch image"
echo '----------------------------'
echo
branch_img_name="${NAMESPACE}/${NAME}-${BRANCH}:${TAG}"
build-branch ${dev_img_name} ${branch_img_name}
echo


echo
echo '############################'
echo "start building test image"
echo '----------------------------'
echo
test_img_name=test:latest
build-test ${branch_img_name} ${test_img_name}
echo
echo '############################'
echo "run code checks and tests in test image"
echo '----------------------------'
echo
docker run \
    ${test_img_name} \
        check-n-test ${PY_PKG_NAME} $COV_FAIL_UNDER


end_time=$(date)
echo
echo "Started at ${start_time}"
echo "Finished at ${end_time}"
echo