#!/bin/bash

# Do not use space in directory and file names in ${HOME}/work and under it.


set -o errexit
set -o nounset
set -o pipefail

USAGE=$(cat <<'EOF'
Usage:

   run-docker [options] <image-name>[:tag] [<cmd> [cmd-args]]

where

`image-name` is like 'zppz/py3', etc.
If image tag is not specified, the latest tag is inferred and used.

`cmd` is the command to be run within the container, followed by arguments to the command.
(Default: /bin/bash)
EOF
)

if [[ $# < 1 ]]; then
    >&2 echo "${USAGE}"
    exit 1
fi


imagename=""
name=""  # container's name
command=/bin/bash  # the command to be run within the container
args=""  # args to `command`
opts=""  # args to `docker run`
nb_port=8888
gpu_devices=all

# You can specify specific GPUs to use, e.g.
# -e NVIDIA_VISIBLE_DEVICES=none
# -e NVIDIA_VISIBLE_DEVICES=0,1,3
# -e NVIDIA_VISIBLE_DEVICES=all

# To restrict memory usage, do something like
# --memory=8g
# Default is unlimited.
#
# See https://georgeoffley.com/blog/shared-memory-in-docker.html


# Parse arguments.
# There are two sets of arguments: those before image-name, and those after.
# For those before, some are parsed; the rest are forwarded to `docker run` as is.
# For those after, the first is the command to be executed within the container;
# the rest are arguments to the command.
while [[ $# > 0 ]]; do
    if [[ "${imagename}" == "" ]]; then
        if [[ "$1" == -v ]]; then
            # volume mapping, e.g.
            #   -v /tmp/data:/home/docker-user/data
            shift
            opts="${opts} -v $1"
        elif [[ "$1" == -p ]]; then
            # Port forwarding, e.g.
            #   -p 8080:8080
            shift
            opts="${opts} -p $1"
        elif [[ "$1" == -e ]]; then
            # Set env var, e.g.
            #   -e MYNAME=abc
            shift
            if [[ "$1" == NVIDIA_VISIBLE_DEVICES=* ]]; then
                zz="$1"
                gpu_devices="${zz#*=}"
            else
                opts="${opts} -e $1"
            fi
        elif [[ "$1" == --nb_port ]]; then
            # Port number for Jupyter Notebook.
            # Use this to avoid "port is being used" error.
            shift
            nb_port="$1"
        elif [[ "$1" == --nb_port=* ]]; then
            nb_port="$1"
            nb_port="${nb_port#*=}"

        elif [[ "$1" == -* ]]; then
            # Every other argument is captured and passed on to `docker run`.
            # For example, if there is an option called `--volume` which sets
            # something called 'volume', you may specify it like this
            #
            #   --volume=30
            #
            # You can not do
            #
            #   --volume 30
            #
            # because `run-docker` does not explicitly capture this option,
            # hence it does not know this option has two parts.
            # The same idea applies to other options.
            opts="${opts} $1"
        else
            imagename="$1"
        fi
        shift
    else
        # After `imagename`.
        command="$1"
        shift
        if [[ $# > 0 ]]; then
            args="$@"
        fi
        break
    fi
done

if [[ "${imagename}" == "" ]]; then
    >&2 echo "${USAGE}"
    exit 1
fi

HOSTWORKDIR="${HOME-/tmp}/work"
DOCKERHOMEDIR="/home/docker-user"
TINY=${TINY:-zppz/tiny:22.12.11}


if [[ "${imagename}" != *:* && "${imagename}" != */* ]]; then
    # The image name is a single word: no namespace, no tag.
    # If it is the name of a repo in `~/work/src/`, then
    # use the local dev image for the repo.
    # The image must have been built previously using
    # the script `run` in the repo directory.
    if [ -d "${HOSTWORKDIR}/src/${imagename}" ]; then
        # It is a source repo.
        imagename=${imagename}:dev
    elif [[ ${imagename} == data ]]; then
        # Special name to inspect content of the data volume.
        imagename=zppz/py3
    elif [[ ${imagename} == py3 ]]; then
        imagename=zppz/py3
    fi
    # If none the above, it's not a source repo.
    # Assume it's a shorthand for a frozen image.
fi

if [[ "${imagename}" == *:dev ]]; then
    # 'dev' is a special tag used by local dev images.
    IMAGENAME=${imagename}
    imagename=${IMAGENAME%:dev}  # remove the ':dev" tag
    imageversion=dev
    PROJ=${imagename}

    HOSTSRCDIR="${HOSTWORKDIR}/src/${PROJ}"
    if [ ! -d "${HOSTSRCDIR}" ]; then
        >&2 echo Cannot find source directory \"${HOSTSRCDIR}\"
        exit 1
    fi

    opts="${opts} -v ${HOSTSRCDIR}:${DOCKERHOMEDIR}/${PROJ} --workdir=${DOCKERHOMEDIR}/${PROJ}"
    opts="${opts} -e PYTHONPATH=${DOCKERHOMEDIR}/${PROJ}/src"
else
    if (( $(echo "${imagename}" | tr -cd '/' | wc -c) < 2 )); then
        # `$imagename` does not contain more than one '/', hence is not
        # a full Docker image name.
        cmd="$(docker run --rm ${TINY} cat /tools/find-image)"
        IMAGENAME=$(bash -c "${cmd}" -- ${imagename})

        if [ -z ${IMAGENAME} ]; then
            >&2 echo Could not find image ${imagename}
            exit 1
        fi
    else
        # `$imagename` is the full name.
        IMAGENAME="${imagename}"
    fi

    imageversion=${IMAGENAME##*:}  # remove the longest substr from front
    imagename=${IMAGENAME%:*}  # remove the shortest substr from back
    imagename=${imagename##*/}  # remove namespace, keeping the last word only
    PROJ=
fi
# `$IMAGENAME` is the full name including url, namespace, etc.
# ${IMAGENAME}=[namespace.../]${imagename}:${imageversion}
# `$imagename` contains neither namespace nor tag.


DATAVOLUME=docker-data-volume
MOUNTPOINT="${DOCKERHOMEDIR}/mnt"
opts="${opts} --mount source=${DATAVOLUME},target=${MOUNTPOINT}"


if [[ "${args}" == '' && " /bin/bash /bin/sh /usr/bin/bash /usr/bin/sh bash sh python ptpython ptipython ipython " == *" ${command} "* ]]; then
    opts="${opts} -it"
fi

if [[ " ${opts} " != *" --name="* ]]; then
    # User did not specify a name for the container.
    name="$(whoami)-$(TZ=America/Los_Angeles date +%Y%m%d-%H%M%S)-pacific"
    opts="${opts} --name=${name}"
fi

if [[ " ${opts} " != *" --shm-size="* ]]; then
    # User did not specify shared memory size.
    opts="${opts} --shm-size=2gb"
fi

if [[ " ${opts} " != *" --restart="* && " ${opts}} " != *" -d "* ]]; then
    # User did not specify '--restart=' or '-d'
    opts="${opts} --rm"
fi

if [[ "$(which nvidia-smi 2>/dev/null)" != '' && "${gpu_devices}" != none ]]; then
    opts="${opts} --runtime=nvidia"
    opts="${opts} -e NVIDIA_VISIBLE_DEVICES=${gpu_devices}"
    # or --gpus=all ?
    # TODO: look into the option `--gpus` to `docker run`.
fi

opts="${opts} -e HOST_NAME=$(uname) -e HOST_WHOAMI=$(whoami)"
if [[ "$(uname)" == Linux ]]; then
    # opts="${opts} -e HOST_IP=$(hostname -i)"
    opts="${opts} -e HOST_IP=$(ip route get 1 | awk '{gsub("^.*src ",""); print $1; exit}')"
elif [[ "$(uname)" == Darwin ]]; then
    opts="${opts} -e HOST_IP=$(ipconfig getifaddr en0)"
fi

if [[ "${command}" == "notebook" ]]; then
    opts="${opts} --expose=${nb_port} -p ${nb_port}:${nb_port}"
    opts="${opts} -e JUPYTER_DATA_DIR=${MOUNTPOINT}/tmp/.jupyter/data"
    opts="${opts} -e JUPYTER_RUNTIME_DIR=${MOUNTPOINT}/tmp/.jupyter/runtime"
    opts="${opts} -e JUPYTERLAB_WORKSPACES_DIR=${MOUNTPOINT}/tmp/.jupyter/workspaces -e JUPYTERLAB_SETTINGS_DIR=${MOUNTPOINT}/tmp/.jupyter/settings"
    # command="jupyter lab --port=${nb_port} --no-browser --ip=0.0.0.0 --NotebookApp.notebook_dir='${DOCKERHOMEDIR}/${PROJ}' --NotebookApp.token=''"
    command="jupyter lab --port=${nb_port} --no-browser --ip=0.0.0.0 --NotebookApp.token=''"
fi


opts="${opts}
--user=docker-user
-e IMAGE_NAME=${imagename}
-e IMAGE_VERSION=${imageversion}
-e TZ=America/Los_Angeles
--init"



docker run ${opts} ${IMAGENAME} ${command} ${args}

